### ISSUE TITLE
excise 5 STYLISH CSS verify wrong

### ISSUE THREAD

**Issue by backsapce** [azat-co/expressworks#32]
i have post the official solution but verify got wrong 

```bash
$ expressworks verify  expressword.js 
Verifying "STYLISH CSS"...

ACTUAL                             EXPECTED
------                             --------
"Error: EACCES, open &#39;/usr/local/lib/node_modules/expressworks/problems/stylish_css/public/main.css&#39;"    "Error: EACCES, open &#39;/usr/local/lib/node_modules/expressworks/problems/stylish_css/public/main.css&#39;"
""                              != null                           
# FAIL

Your solution to STYLISH CSS didn't match the expected output.
Try again!
```

the official solution 

``` js
var app = express()

app.use(require('stylus').middleware(process.argv[3]));
app.use(express.static(process.argv[3]));


app.listen(process.argv[2])
```

**Comment by aaaaargZombies** [comment]
Sooooooo, my code works when I run it with node and I get the disered response in the browser.
Previously I was getting what looked like errors on the 'expected' side of the checker and what looked like the correct answer on mine.
Now for some reason the verify part of the program seems to have completely given up on me all  I get is this and a blinking cursor in my terminal. 

```shell 
Verifying "STYLISH CSS"...

ACTUAL                             EXPECTED
------                             --------

// blinking cursor of doom.
```
Perhaps running it as root will give it the push it needs to churn through the test but alas it won't give me the tick on my users account and I wont have that nice complete feeling....

my code below...
```javascript
var express		= require('express'),
	app			= express(),
	dir 		= process.argv[3],
	port		= process.argv[2];

app.use(express.static(dir));
app.use(require('stylus').middleware(dir));

app.listen(Number(port));
```

**Comment by aaaaargZombies** [comment]
ok I fixed it.

running my initial code to test it with my browser must have left something using my port so I did ```killall node```  to clear what ever my last program had left floating around. I then got the EACCES error some people are refering to above. I changed the file permisions in the relevant folder,

```shell  
su -c 'chown GROUP:USR /usr/lib/node_modules/expressworks/problems/stylish_css/public/*' 
```

which is a bit hacky, I suspect if you installed *expressworks* it all locally as described in the README you wouldn't have that problem because you should have all the correct permisions already. neither solution is particually satisfying but atleast it passed the test.

**Comment by mhurwicz** [comment]
The official solution provided in the first comment works for me now.
